/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TARGA_SIZE 8
#define PATENTE_SIZE 6
#define MAX_TIPO_SIZE 7
#define CHAR_FOLDER_SIZE 13
#define MAX_PRENOTAZIONI_SIZE 6

struct Riga {
	char targa[TARGA_SIZE];
	char patente[PATENTE_SIZE];
	char tipo[MAX_TIPO_SIZE];
	char img[CHAR_FOLDER_SIZE];
};
typedef struct Riga Riga;

struct InputVisualizza {
	char tipo[MAX_TIPO_SIZE];
};
typedef struct InputVisualizza InputVisualizza;

struct OutputVisualizza {
	Riga prenotazioni[MAX_PRENOTAZIONI_SIZE];
	int numPrenotazioni;
};
typedef struct OutputVisualizza OutputVisualizza;

struct InputAggiorna {
	char targa[TARGA_SIZE];
	char patente[PATENTE_SIZE];
};
typedef struct InputAggiorna InputAggiorna;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define visualizza_prenotazioni 1
extern  OutputVisualizza * visualizza_prenotazioni_1(InputVisualizza *, CLIENT *);
extern  OutputVisualizza * visualizza_prenotazioni_1_svc(InputVisualizza *, struct svc_req *);
#define aggiorna_licenza 2
extern  int * aggiorna_licenza_1(InputAggiorna *, CLIENT *);
extern  int * aggiorna_licenza_1_svc(InputAggiorna *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define visualizza_prenotazioni 1
extern  OutputVisualizza * visualizza_prenotazioni_1();
extern  OutputVisualizza * visualizza_prenotazioni_1_svc();
#define aggiorna_licenza 2
extern  int * aggiorna_licenza_1();
extern  int * aggiorna_licenza_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Riga (XDR *, Riga*);
extern  bool_t xdr_InputVisualizza (XDR *, InputVisualizza*);
extern  bool_t xdr_OutputVisualizza (XDR *, OutputVisualizza*);
extern  bool_t xdr_InputAggiorna (XDR *, InputAggiorna*);

#else /* K&R C */
extern bool_t xdr_Riga ();
extern bool_t xdr_InputVisualizza ();
extern bool_t xdr_OutputVisualizza ();
extern bool_t xdr_InputAggiorna ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
